services:
  mongodb:
    image: mongo:latest
    container_name: neurochair-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=neurochair
    volumes:
      - mongodb_data:/data/db
    networks:
      - neurochair-network

  # Mosquitto MQTT Broker for IoT communication
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: neurochair-mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt-broker/config:/mosquitto/config
      - ./mqtt-broker/data:/mosquitto/data
      - ./mqtt-broker/log:/mosquitto/log
    networks:
      - neurochair-network

  # Python Backend for data processing
  backend:
    build: ./analytics
    container_name: neurochair-backend
    depends_on:
      - mongodb
      - mqtt-broker
    environment:
      - MQTT_BROKER=mqtt-broker
      - MONGO_URI=mongodb://mongodb:27017/neurochair
    networks:
      - neurochair-network

  # Dashboard (Plotly Dash)
  dashboard:
    build: ./dashboard
    container_name: neurochair-dashboard
    ports:
      - "8050:8050"
    depends_on:
      - mongodb
      - backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017/neurochair
    volumes:
      - ./Datasets:/app/Datasets
    networks:
      - neurochair-network

volumes:
  mongodb_data:


networks:
  neurochair-network:
    driver: bridge
